In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re

In [5]:
df.Delivery_PANDA = df.Delivery_PANDA.apply(lambda x: re.sub("HK\$ ","",x))
df.Delivery_PANDA = df.Delivery_PANDA.apply(lambda x: re.sub(" delivery fee","",x))

In [3]:
df = pd.read_csv("big_df_UBERXPANDA.csv",index_col=0)

In [6]:
d_roo = pd.read_csv("deliveroo_page.csv", header=None)

In [14]:
import re
def getEng(context):
    context = context# convert context from str to unicode
    filtrate = re.compile(u'[\u4E00-\u9FA5]') # non-Chinese unicode range
    context = filtrate.sub(r'', context) # remove all non-Chinese characters
    # context = context.encode("utf-8") # convert unicode back to str
    return context

In [17]:
d_roo.columns = ["Merge",1,2,3,4,5]
d_roo.Merge = d_roo.Merge.apply(lambda x: x.lower() if isinstance(x,str) else x)
d_roo.Merge = d_roo.Merge.apply(lambda x: getEng(x) if isinstance(x,str) else x)
d_roo

,Merge,1,2,3,4,5
0,tsui wah restaurant,4.5,500+,"['Hong Kongese', 'Cantonese', 'Curry', 'Noodle...","Unit1-3,G/F,Causeway Bay Commercial Building,1...","['$46.00', '$46.00', '$45.00', '$55.00', '$198..."
1,ichiran,4.6,500+,"['Japanese', 'Ramen', 'Noodles']","Shop F-I, 440 Jaffe Rd, Causeway Bay,, Hong Ko...","['$30.00', '$109.00', '$24.00', '$20.00', '$75..."
2,poke hk - causeway bay,4.7,500+,"['Hawaiian', 'Poke', 'Salads', 'Sandwiches', '...","G/F, 124 Leighton Road, Causeway Bay, Hong Kong,","['$88.00', '$98.00', '$88.00', '$88.00', '$66...."
3,7-eleven,4.4,49,"['Grocery', 'Snacks', 'Alcohol', 'Drinks', 'Sa...",Portion of Unit No.2 on the Portion of the G/F...,"['$108.00', '$149.90', '$55.00', '$12.00', '$1..."
4,wing nin noodle,4.7,500+,"['Hong Kongese', 'Noodles']","G/F, 482 Jaffe Road, Causeway Bay, Hong Kong,","['$88.00', '$88.00', '$29.00', '$29.00', '$1,2..."
...,...,...,...,...,...,...
214,regal palace,4.4,169,"['Cantonese', 'Chicken', 'Chinese', 'Noodles',...","3/F, Regal Hong Kong Hotel, 88 Yee Wo Street, ...","['$68.00', '$88.00', '$78.00', '$138.00', '$88..."
215,kam sheung tim,4.5,500+,['Juices'],"Shop A, 64 Wharf Road, North Point, Hong Kong,","['$40.00', '$38.00', '$38.00', '$22.00', '$28...."
216,via tokyo cafe,4.5,244,"['Japanese', 'Tea', 'Cakes', 'Dessert', 'Bubbl...","Shop 1A-1B, G/F, Leishun Court, 106-126 Leight...","['$96.00', '$144.00', '$192.00', '$43.00', '$4..."
217,hee kee fried crab expert,4.4,446,"['Chinese', 'Cantonese', 'Seafood']","Shop 1-4, G/F, 379 Jaffe Road, Wan Chai,, Hong...","['$998.00', '$1,199.00', '$1,326.00', '$348.00..."
218,top grade hot pot,4.7,84,"['Chinese', 'Seafood', 'Hot Pot']","天后清風街5-7號富豐樓地舖,, Hong Kong,","['$288.00', '$288.00', '$238.00', '$158.00', '..."

In [6]:
df.Exclusivity.value_counts()

0    95
1    16
Name: Exclusivity, dtype: int64

In [7]:
df[df["Cuisine_single_PANDA"] != df["Cuisine_single_UBER"]]

,Merge,Address,Average_price_PANDA,Average_price_UBER,Cuisine_PANDA,Cuisine_UBER,Cuisine_single_PANDA,Cuisine_single_UBER,Delivery_PANDA,Delivery_UBER,Dollar_signs,Exclusivity,Food_type,Name_PANDA,Name_UBER,Promotion,Ratings_PANDA,Ratings_UBER,Reviews_PANDA,Reviews_UBER
1,subway,"218 Electric Rd, North Point, Hong Kong, SHOP ...",39.484848,44.0,"['Burger', 'Western', 'Salad']","['Fast Food', 'Western', 'Vegan']",Burger,Fast Food,12,19.0,2.0,0,$$ • Fast Food\r\n • \r\nWestern\r\n • \r\nVegan,subway (fortress hill),subway (fortress hill),NaN,4.5/5,4.5,605.0,59
3,europa tea foundry,"22 Yee Wo St, Causeway Bay, Hong Kong, Shop 3,...",43.692308,40.0,"['Drinks', 'Hong Kong']",['Bubble Tea'],Drinks,Bubble Tea,20,24.0,1.0,0,$ • Bubble Tea,europa tea foundry (cwb),木衛二鑄茶所 europa tea foundry (銅鑼灣 causeway bay),NaN,4.7/5,4.9,215.0,50
4,cupfy,"Hysan Place, 500 Hennessy Road, Causeway Bay, ...",32.740541,35.0,"['Drinks', 'Taiwanese', 'Only on foodpanda']","['Bubble Tea', 'Desserts', 'Coffee and tea']",Drinks,Bubble Tea,20,19.0,2.0,1,$$ • Bubble Tea\r\n • \r\nDesserts\r\n • \r\nC...,cupfy (causeway bay),cupfy 走杯 (銅鑼灣 causeway bay),10% off $200,4.6/5,4.8,23.0,22
5,cali-mex bar & grill,"Shop 20-21, Aia Tower, 183 Electric Rd, North ...",116.617886,123.0,"['American', 'Western', 'Mexican', 'Salad', 'D...","['Mexican', 'Healthy', 'Vegetarian', 'Burger',...",American,Mexican,12,14.0,1.0,0,$ • Mexican\r\n • \r\nHealthy\r\n • \r\nVegeta...,cali-mex bar & grill (north point),cali-mex bar & grill (north point),NaN,4.4/5,4.5,1284.0,61
6,bhc,"535 Jaffe Rd, Shop B03, Basement, Tower 535,, ...",145.441860,139.0,"['Fast Food', 'Korean']",['Korean'],Fast Food,Korean,20,NaN,1.0,0,$ • Korean,bhc (causeway bay),bhc (causeway bay),NaN,4.4/5,4.1,190.0,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,the graces restaurant,"Lee Theatre Plaza, 99 Percival Street, Causewa...",113.116279,40.0,"['Chinese', 'Soup']",['Cantonese'],Chinese,Cantonese,20,NaN,3.0,0,$$$ • Cantonese,the graces restaurant (cwb),玉桃軒酒家 the graces restaurant (causeway bay),NaN,4.5/5,NaN,NaN,NaN
106,clay pot indian restaurant,"Hong Kong, North Point, 北角電氣道229號電氣道市政大廈2樓cf5號...",68.111111,91.0,"['Seafood', 'Indian']",['Indian'],Seafood,Indian,17,NaN,2.0,0,$$ • Indian,clay pot indian restaurant,clay pot indian restaurant 烤爐印度餐廳,NaN,4.4/5,NaN,207.0,NaN
107,tian tian hainanese chicken rice,"9 Kingston St, Shop H2, G/F, Fashion Walk,\r\n...",82.700000,369.0,"['Singaporean', 'Cashback', 'Dine-in Price', '...",['South East Asian'],Singaporean,South East Asian,20,NaN,2.0,0,$$ • South East Asian,tian tian hainanese chicken rice (causeway bay),天天海南雞飯 tian tian hainanese chicken rice (銅鑼灣 c...,20% off $100,4.2/5,4.4,338.0,(11)
108,shun hing,"5 Ormsby St, Tai Hang, Hong Kong, G/F, ,\r\n •...",30.600000,18.0,"['Sandwich', 'Chinese', 'Carousel Deals']",['Cantonese'],Sandwich,Cantonese,17,NaN,2.0,0,$$ • Cantonese,shun hing (tai hang) restaurant,順興茶餐廳 shun hing (tai hang) restaurant,10% off $80,4.6/5,NaN,389.0,NaN
110,elementary,"15 School St, Tai Hang, Hong Kong, G/F, ,\r\n ...",178.088608,145.0,"['European', 'Pasta', 'Favourites by foodpanda...",['Western'],European,Western,17,NaN,2.0,0,$$ • Western,elementary,elementary,NaN,4.6/5,NaN,100.0,NaN

In [8]:
df[ df.Exclusivity == 1]

,Merge,Address,Average_price_PANDA,Average_price_UBER,Cuisine_PANDA,Cuisine_UBER,Cuisine_single_PANDA,Cuisine_single_UBER,Delivery_PANDA,Delivery_UBER,Dollar_signs,Exclusivity,Food_type,Name_PANDA,Name_UBER,Promotion,Ratings_PANDA,Ratings_UBER,Reviews_PANDA,Reviews_UBER
4,cupfy,"Hysan Place, 500 Hennessy Road, Causeway Bay, ...",32.740541,35.0,"['Drinks', 'Taiwanese', 'Only on foodpanda']","['Bubble Tea', 'Desserts', 'Coffee and tea']",Drinks,Bubble Tea,20,19.0,2.0,1,$$ • Bubble Tea\r\n • \r\nDesserts\r\n • \r\nC...,cupfy (causeway bay),cupfy 走杯 (銅鑼灣 causeway bay),10% off $200,4.6/5,4.8,23.0,22
10,doner kebab,"Fu Lee Loy Shopping Centre, 9-27 King Wah Road...",74.400000,69.0,"['Middle Eastern', 'Only on foodpanda', 'Dine-...",['Middle Eastern'],Middle Eastern,Middle Eastern,12,14.0,2.0,1,$$ • Middle Eastern,doner kebab,doner kebab,10% off $80,4.2/5,NaN,50.0,NaN
11,ming ming cart noodle bar,"89 Hennessy Rd, Wan Chai, Hong Kong, G/F, ,\r\...",15.152055,34.0,"['Noodles', 'Hong Kong', 'Only on foodpanda', ...",['Chinese'],Noodles,Chinese,17,24.0,1.0,1,$ • Chinese,ming ming cart noodle bar (north point),明明車仔麵專門店 ming ming cart noodle bar (軒尼詩道89號近修頓球場),10% off $80,4.3/5,4.6,1434.0,100
12,ming ming cart noodle bar,"290 Hennessy Rd, Wan Chai, Hong Kong, G/F, ,\r...",15.152055,34.0,"['Noodles', 'Hong Kong', 'Only on foodpanda', ...",['Chinese'],Noodles,Chinese,17,24.0,1.0,1,$ • Chinese,ming ming cart noodle bar (north point),明明車仔麵專門店 ming ming cart noodle bar (軒尼詩道290號近英...,10% off $80,4.3/5,4.6,1434.0,60
22,tiger sugar,"Hong Kong, 灣仔柯布連道2號修頓中心地下4號舖, Shop 4, G/F, Sou...",34.302326,34.0,"['Drinks', 'Taiwanese', 'Only on foodpanda', '...",['Bubble Tea'],Drinks,Bubble Tea,20,24.0,2.0,1,$$ • Bubble Tea,tiger sugar (causeway bay),tiger sugar 老虎堂黑糖專売 (wan chai 灣仔),NaN,4.5/5,4.5,166.0,22
23,tiger sugar,"Hong Kong, 銅鑼灣渣甸街36號地下3號舖, Shop 3, G/F, ,\r\n ...",34.302326,34.0,"['Drinks', 'Taiwanese', 'Only on foodpanda', '...",['Bubble Tea'],Drinks,Bubble Tea,20,NaN,2.0,1,$$ • Bubble Tea,tiger sugar (causeway bay),tiger sugar 老虎堂黑糖專売 (causeway bay 銅鑼灣),NaN,4.5/5,4.6,166.0,(12)
37,istanbul kebab corner,"Fu Lee Loy Shopping Centre, 9-27 King Wah Road...",61.493023,69.0,"['Middle Eastern', 'Only on foodpanda', 'Dine-...","['Indian', 'Pakistani', 'Turkish', 'Pizza']",Middle Eastern,Indian,12,14.0,2.0,1,$$ • Indian\r\n • \r\nPakistani\r\n • \r\nTurk...,istanbul kebab corner,istanbul kebab corner,10% off $80,4/5,NaN,33.0,NaN
38,dazzling cafe,"311 Gloucester Rd, Shop 313-314, 3/F, Windsor ...",68.735294,71.0,"['Taiwanese', 'Only on foodpanda', 'Dine-in Pr...","['Taiwanese', 'Cafe', 'Asian Fusion']",Taiwanese,Taiwanese,20,19.0,2.0,1,$$ • Taiwanese\r\n • \r\nCafe\r\n • \r\nAsian ...,dazzling cafe (causeway bay),dazzling cafe (windsor house),NaN,4.5/5,NaN,72.0,NaN
39,hot dog link,"27 Mercury St, Causeway Bay, Hong Kong, Shop C...",39.556818,34.0,"['German', 'Only on foodpanda', 'Dine-in Price']","['American', 'Allergy friendly']",German,American,12,19.0,2.0,1,$$ • American\r\n • \r\nAllergy friendly,hot dog link (tin hau),德國熱狗 hot dog link(tin hau),NaN,4.6/5,4.4,169.0,31
48,my cup of tea,"5 Haven St, Shop 3&6, G/F, Lei Shun Court, Wan...",52.137931,46.0,"['Sandwich', 'Hong Kong', 'Only on foodpanda',...",['Cantonese'],Sandwich,Cantonese,12,19.0,2.0,1,$$ • Cantonese,my cup of tea (fortress hill),my cup of tea 我杯茶 (銅鑼灣),NaN,4.4/5,NaN,87.0,NaN
49,my cup of tea,"5 Haven St, Shop 3&6, G/F, Lei Shun Court, Wan...",52.137931,46.0,"['Hong Kong', 'Sandwich', 'Only on foodpanda']",['Cantonese'],Hong Kong,Cantonese,20,19.0,2.0,1,$$ • Cantonese,my cup of tea (causeway bay),my cup of tea 我杯茶 (銅鑼灣),NaN,4.5/5,NaN,45.0,NaN
50,my cup of tea,"12 Wang On Rd, Shop 5, G/F, Wang Fai Mansion, ...",52.137931,46.0,"['Sandwich', 'Hong Kong', 'Only on foodpanda',...",['Cantonese'],Sandwich,Cantonese,12,NaN,2.0,1,$$ • Cantonese,my cup of tea (fortress hill),my cup of tea 我杯茶 (北角),NaN,4.4/5,NaN,87.0,NaN
51,my cup of tea,"12 Wang On Rd, Shop 5, G/F, Wang Fai Mansion, ...",52.137931,46.0,"['Hong Kong', 'Sandwich', 'Only on foodpanda']",['Cantonese'],Hong Kong,Cantonese,20,NaN,2.0,1,$$ • Cantonese,my cup of tea (causeway bay),my cup of tea 我杯茶 (北角),NaN,4.5/5,NaN,45.0,NaN
66,around wellington,"Circle Tower, 28 Tang Lung St, Bowrington, Hon...",98.258824,65.0,"['Pizza', 'Hong Kong', 'Only on foodpanda', 'P...",['Western'],Pizza,Western,20,19.0,2.0,1,$$ • Western,around wellington,around wellington,10% off $300,4.9/5,NaN,24.0,NaN
75,moo moo plus,"59-65 Paterson Street, Fashion Walk, Causeway ...",147.093333,137.0,"['Burger', 'Pizza', 'Western', 'Only on foodpa...","['Burger', 'American', 'Western']",Burger,Burger,20,19.0,3.0,1,$$$ • Burger\r\n • \r\nAmerican\r\n • \r\nWestern,moo moo plus,moo moo plus,20% off $100,4.5/5,NaN,10.0,NaN
96,coffee obsession,"4-8 Boat St, North Point, Hong Kong, Shop E, G...",28.675000,56.0,"['Drinks', 'Western', 'Only on foodpanda', 'Di...","['Cafe', 'Western', 'European']",Drinks,Cafe,12,NaN,2.0,1,$$ • Cafe\r\n • \r\nWestern\r\n • \r\nEuropean,coffee obsession,coffee obsession,NaN,5/5,NaN,2.0,NaN

In [9]:
df.head()

,Merge,Address,Average_price_PANDA,Average_price_UBER,Cuisine_PANDA,Cuisine_UBER,Cuisine_single_PANDA,Cuisine_single_UBER,Delivery_PANDA,Delivery_UBER,Dollar_signs,Exclusivity,Food_type,Name_PANDA,Name_UBER,Promotion,Ratings_PANDA,Ratings_UBER,Reviews_PANDA,Reviews_UBER
0,pho 5,"17 Tsing Fung Street, G/F, Causeway Bay, Hong ...",37.096774,48.0,"['Vietnamese', 'Salad', 'Limited Offers', 'Din...","['Vietnamese', 'Allergy friendly', 'Family fri...",Vietnamese,Vietnamese,12,14.0,2.0,0,$$ • Vietnamese\r\n • \r\nAllergy friendly\r\n...,pho 5 (tin hau),火五越式牛肉粉專門店 pho 5 (tin hau),50% off,4/5,4.2,804.0,100
1,subway,"218 Electric Rd, North Point, Hong Kong, SHOP ...",39.484848,44.0,"['Burger', 'Western', 'Salad']","['Fast Food', 'Western', 'Vegan']",Burger,Fast Food,12,19.0,2.0,0,$$ • Fast Food\r\n • \r\nWestern\r\n • \r\nVegan,subway (fortress hill),subway (fortress hill),NaN,4.5/5,4.5,605.0,59
2,jiu fen full,"Universal Commercial House, 4 Shell St, Causew...",31.249180,29.0,"['Taiwanese', 'Tea Time', 'Carousel Deals']","['Taiwanese', 'Family friendly']",Taiwanese,Taiwanese,12,19.0,2.0,0,$$ • Taiwanese\r\n • \r\nFamily friendly,jiu fen full (north point),九份飽 jiu fen full (蜆殼街 shell street),10% off $80,4.4/5,4.5,1035.0,100
3,europa tea foundry,"22 Yee Wo St, Causeway Bay, Hong Kong, Shop 3,...",43.692308,40.0,"['Drinks', 'Hong Kong']",['Bubble Tea'],Drinks,Bubble Tea,20,24.0,1.0,0,$ • Bubble Tea,europa tea foundry (cwb),木衛二鑄茶所 europa tea foundry (銅鑼灣 causeway bay),NaN,4.7/5,4.9,215.0,50
4,cupfy,"Hysan Place, 500 Hennessy Road, Causeway Bay, ...",32.740541,35.0,"['Drinks', 'Taiwanese', 'Only on foodpanda']","['Bubble Tea', 'Desserts', 'Coffee and tea']",Drinks,Bubble Tea,20,19.0,2.0,1,$$ • Bubble Tea\r\n • \r\nDesserts\r\n • \r\nC...,cupfy (causeway bay),cupfy 走杯 (銅鑼灣 causeway bay),10% off $200,4.6/5,4.8,23.0,22